name: revup
description: A Very Good App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  auto_route: ^4.2.1
  auto_size_text: ^3.0.0
  bloc: ^8.0.3
  build_runner: ^2.1.11
  cached_network_image: ^3.2.1
  connectivity_plus: ^2.3.5
  dartz: ^0.10.1
  dio: ^4.0.1
  firebase_core: ^1.19.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_form_builder: ^7.3.1
  flutter_form_field_validator: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.0
  form_builder_validators: ^8.1.1
  freezed_annotation: ^2.0.3
  hive: ^2.2.3
  intl: ^0.17.0
  introduction_screen: ^3.0.1
  json_annotation: ^4.6.0
  revup_core:
    git:
      url: https://github.com/Revup-vn/revup-core.git
      ref: main
      version: ^1.1.1+0
  shared_preferences: ^2.0.15

dev_dependencies:
  auto_route_generator: ^4.0.0
  bloc_test: ^9.0.3
  dart_code_metrics: ^4.16.0
  dependency_validator: ^3.2.2
  flutter_gen_runner: ^4.3.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  import_sorter: ^4.6.0
  json_serializable: ^6.3.1
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.1

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
import_sorter:
  comments: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/screens/
