// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        break;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuN-H0vkxIk9_wo9EpkevoxkSITpWtIOk',
    appId: '1:755978697752:android:1e74951b183f4adf71176d',
    messagingSenderId: '755978697752',
    projectId: 'revup-4402d',
    storageBucket: 'revup-4402d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgGl7FI6hCwJ3r7bu5YdvD3hmS9mZz-Gk',
    appId: '1:755978697752:ios:61b15c74b342c78e71176d',
    messagingSenderId: '755978697752',
    projectId: 'revup-4402d',
    storageBucket: 'revup-4402d.appspot.com',
    androidClientId:
        '755978697752-01v37rkvgggcfirtqoic8atrcavis7g0.apps.googleusercontent.com',
    iosClientId:
        '755978697752-fkt2o0b7kq6t12h17t4krdbiome09u5n.apps.googleusercontent.com',
    iosBundleId: 'vn.com.revup',
  );
}
